name: pr_env_var_docs

# cancels in-progress jobs on this pull request
# avoids wasted work when a new commit is pushed
concurrency:
  group: pr-server-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'env-var-docs/**'
      - 'server/conf/application.conf'
      - 'server/conf/env-var-docs.json'
      - '.github/workflows/pr_env_var_docs.yaml'

jobs:
  run-validations:
    runs-on: ubuntu-latest
    env:
      APPLICATION_CONF_PATH: server/conf/application.conf
      ENV_VAR_DOCS_PATH: server/conf/env-var-docs.json
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install mypy and pytest
        run: pip install mypy pytest

      - name: Run mypy
        run: mypy env-var-docs

      - name: Run pytest
        run: pytest env-var-docs
